### ISSUE TITLE
image store

### ISSUE THREAD

**Issue by delphinus** [delphinus/homebrew-sfmono-square#1]
<img width="762" alt="2018-03-18 21 25 13" src="https://user-images.githubusercontent.com/1239245/37565852-45597362-2af4-11e8-8518-9497a25c47f0.png">

<img width="746" alt="2018-03-18 21 25 09" src="https://user-images.githubusercontent.com/1239245/37565855-4deaeace-2af4-11e8-9eb7-eec9682ebb04.png">

<img width="746" alt="2018-03-18 21 33 03" src="https://user-images.githubusercontent.com/1239245/37565856-5a7a7a34-2af4-11e8-885c-d69a3c1937e3.png">

<img width="746" alt="2018-03-18 21 34 38" src="https://user-images.githubusercontent.com/1239245/37565859-5dd70530-2af4-11e8-9aa6-c0b64c6fab24.png">

<img width="746" alt="2018-03-18 21 34 00" src="https://user-images.githubusercontent.com/1239245/37565861-608ca578-2af4-11e8-82f6-e1a5d911ab24.png">

**Comment by delphinus** [comment]
<img width="598" alt="スクリーンショット 0001-05-23 21 40 50" src="https://user-images.githubusercontent.com/1239245/58253912-802c3480-7da4-11e9-9936-1f68326b9c38.png">

<img width="746" alt="スクリーンショット 0001-05-23 21 47 37" src="https://user-images.githubusercontent.com/1239245/58253927-8e7a5080-7da4-11e9-9d6b-0520cea1438c.png">

<img width="746" alt="スクリーンショット 0001-05-23 21 42 22" src="https://user-images.githubusercontent.com/1239245/58253934-92a66e00-7da4-11e9-983d-1f90f9d8a846.png">

<img width="746" alt="スクリーンショット 0001-05-23 21 43 33" src="https://user-images.githubusercontent.com/1239245/58253939-95a15e80-7da4-11e9-92d9-5e9693cfbccb.png">

**Comment by mhartington** [comment]
Hello. A question about the git log image. How did you achieve this?

**Comment by delphinus** [comment]
@mhartington 

This is from [jonas/tig][] (and this font).

[jonas/tig]: https://github.com/jonas/tig

**Comment by delphinus** [comment]
![0xF6D5@2x](https://user-images.githubusercontent.com/1239245/189081110-055b21d0-6868-43e3-bf9a-20f26f1c8a1b.png)
![0xF6D6@2x](https://user-images.githubusercontent.com/1239245/189081128-96aa06ac-7a38-4cae-964b-87e9ae4f25af.png)
![0xF6D7@2x](https://user-images.githubusercontent.com/1239245/189081145-74953367-fe04-40be-81cd-c937431642b8.png)
![0xF6D8@2x](https://user-images.githubusercontent.com/1239245/189081173-56466aed-056c-4c03-9184-17df58e1799a.png)
![0xF8FF@2x](https://user-images.githubusercontent.com/1239245/189081193-2f0f43e3-2910-4559-99a7-e5c52413645b.png)
![0xFF6D5@2x](https://user-images.githubusercontent.com/1239245/189081906-6034a767-e995-4863-a7cd-608e30e9b690.png)
![0xFF6D6@2x](https://user-images.githubusercontent.com/1239245/189081935-ffef5ed5-5d90-4cac-90ab-caf3c5adaa5f.png)
![0xFF6D7@2x](https://user-images.githubusercontent.com/1239245/189081958-8861eca6-7743-433c-a4cd-8dd06fa6ef74.png)
![0xFF6D8@2x](https://user-images.githubusercontent.com/1239245/189081975-2c3e0a34-3307-49a1-a5f4-0d619bfa0070.png)
![0xFF8FF@2x](https://user-images.githubusercontent.com/1239245/189081984-85e2d466-bdc8-4d44-9eb5-ea2aa2855876.png)

**Comment by delphinus** [comment]
[migu-1m-20200307.tar.gz](https://github.com/delphinus/homebrew-sfmono-square/files/13533559/migu-1m-20200307.tar.gz)
