### ISSUE TITLE
斜体(italic)指定が効かない

### ISSUE THREAD

**Issue by shungo27** [delphinus/homebrew-sfmono-square#10]
Sublime Text と VS Code で確認したのですが、日本語が斜体になりません。

VS Code の設定で、'SF Mono Square' のみの場合、アルファベットも含めて斜体になりませんでした。'SF Mono 1x2', 'SF Mono Square' この設定ではアルファベットのみ斜体になります。

**Comment by delphinus** [comment]
@shungo27 大変時間が掛かりましたがこちら直すことができました。ご確認ください。
