### ISSUE TITLE
brew command failed to download a new SF-Mono.dmg

### ISSUE THREAD

**Issue by Ladicle** [delphinus/homebrew-sfmono-square#46]
The brew command didn't download a new SF-Mono.dmg and failed the hash value check.  It seems that the file is cached because the URL is the same regardless of version.
https://github.com/delphinus/homebrew-sfmono-square/blob/master/sfmono-square.rb#L25

Error message:
```
==> Downloading https://developer.apple.com/design/downloads/SF-Mono.dmg
Already downloaded: /Users/ladicle/Library/Caches/Homebrew/downloads/0460e0518bf6a1c4bf8645a32eab811d8aef26f6e7a24fb44d81e4a237d7afd4--SF-Mono.dmg
Error: SHA256 mismatch
Expected: 61a7d750badddcb9c4af0161aa750dbed42789d34de2facf1781bb48a008e1bd
  Actual: f46a0a74a3e02e9c0304eebe5c8fbbc2211ed32536981df42725c16a0feeebf3
 Archive: /Users/ladicle/Library/Caches/Homebrew/downloads/0460e0518bf6a1c4bf8645a32eab811d8aef26f6e7a24fb44d81e4a237d7afd4--SF-Mono.dmg
To retry an incomplete download, remove the file above.
```

**Comment by delphinus** [comment]
I found hash of `SF-Mono.dmg` is the same as one in the formula.

```sh
curl -L https://developer.apple.com/design/downloads/SF-Mono.dmg | shasum -a256

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   280  100   280    0     0    484      0 --:--:-- --:--:-- --:--:--   484
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     7    0     7    0     0      3      0 --:--:--  0:00:01 --:--:--     9
100 1694k  100 1694k    0     0   609k      0  0:00:02  0:00:02 --:--:-- 2373k
61a7d750badddcb9c4af0161aa750dbed42789d34de2facf1781bb48a008e1bd  -
```

And I got `brew uninstall sfmono-square && brew install sfmono-square` successfully finished. Perhaps your network env seems to have troubles?

**Comment by Ladicle** [comment]
Sorry, I didn't explain it enough. It happened when I updated all formulas using `brew update`.  The hash of the latest version is `61a7d750` in my environment as well.
In other words, it doesn't matter if you don't update. As you pointed out, we can get around by "uninstall and install".

**Comment by delphinus** [comment]
I understand. In usual, Homebrew detects the caches' freshness by differentiating their mtime from `Last-Modified` header. It seems that Apple server does NOT return the header and Homebrew cannot detect caches' freshness suitably.

I will consider how we solves this more robustly...

**Comment by delphinus** [comment]
FYI: Homebrew's logic to detect caches' freshness

https://github.com/Homebrew/brew/blob/593b60fa1b5c8b27b15be30af87cb766482cd502/Library/Homebrew/download_strategy.rb#L297-L318
