### ISSUE TITLE
start harf width is 0xFF61

### ISSUE THREAD

**Issue by AquaBindi** [delphinus/homebrew-sfmono-square#62]
https://github.com/delphinus/homebrew-sfmono-square/blob/5e250037fc0e87638f86b3a0ab3d9a74fb809f81/src/migu1m.py#L13

not 0xFF60

**Comment by delphinus** [comment]
Thx, good catch! I'll fix this.

**Comment by delphinus** [comment]
Sorry for late. This is fixed in v3.0.4.
