### ISSUE TITLE
The width of the half-width space appears doubled in VSCode

### ISSUE THREAD

**Issue by pddg** [delphinus/homebrew-sfmono-square#7]
Hi. I'm a developer and not very familiar with fonts.
Please let me know what happened when using this awesome product.

## Environtment

- macOS 10.14.5 Mojave
- VSCode 1.36.0
- iTerm2 3.2.9
- PyCharm Professional 2019.1.3

I installed the SF Mono Square following your instruction on README. And open the folder containing fonts, then, double clicked and installed them.

## What is the problem?

I want to use this font on VSCode, but the half-width space looks like doubled.

![sf-mono-doubled](https://user-images.githubusercontent.com/14105201/60764354-29b05680-a0c3-11e9-8a45-f6eafcebf9a6.gif)

And the line height behaves strangely with default value `0`. It uses the size of font if it specified `0`.

![スクリーンショット 2019-07-07 14 18 02](https://user-images.githubusercontent.com/14105201/60764419-31bcc600-a0c4-11e9-9031-0f40eb2ce0b2.png)

But I specify the line height manually (as same as editor font size), It behaves normally.

![スクリーンショット 2019-07-07 14 36 09](https://user-images.githubusercontent.com/14105201/60764428-9546f380-a0c4-11e9-9858-80339ab089a3.png)

These behaviors do not appear in other applications such like iTerm2 or PyCharm.

<img width="1552" alt="スクリーンショット 2019-07-07 14 18 25" src="https://user-images.githubusercontent.com/14105201/60764441-d0492700-a0c4-11e9-9bf7-40fc54e4f54f.png">

<img width="934" alt="スクリーンショット 2019-07-07 14 44 37" src="https://user-images.githubusercontent.com/14105201/60764484-c4119980-a0c5-11e9-90c2-2f0f2ae268ce.png">

This phenomenon could not be confirmed with other fonts (Menlo, Monaco, [Ricty Diminished with-icons](https://github.com/iij/fontmerger/tree/master/sample)...etc).

## Question

1. Is this a bug?
2. Do you know the workaround for this?

**Comment by delphinus** [comment]
hmm... It seems that VSCode sees some other properties in fonts than other apps. I will investigate this deeper. Wait minutes.

**Comment by delphinus** [comment]
### for the “space” glyph

I've released [v1.1.1][111] for a temporal workaround for this. This installs source fonts named “SF Mono 1x2”.

[111]: https://github.com/delphinus/homebrew-sfmono-square/releases/tag/v1.1.1

<img width="115" alt="スクリーンショット 0001-07-08 15 03 44" src="https://user-images.githubusercontent.com/1239245/60786583-191ae180-a192-11e9-91f7-080f30c4c0f0.png">

SF Mono 1x2 is a part of SF Mono Square and has half-width glyphs only. You can set it as `fontFamily` in VSCode, and SF Mono Square as the fallback.

* `"SF Mono 1x2", "SF Mono Square"`

<img width="233" alt="スクリーンショット 0001-07-08 15 09 08" src="https://user-images.githubusercontent.com/1239245/60786714-7a42b500-a192-11e9-8d55-52e5990a7718.png">

This makes good for such texts above.

<img width="82" alt="スクリーンショット 0001-07-08 15 25 46" src="https://user-images.githubusercontent.com/1239245/60787412-aeb77080-a194-11e9-9a5b-389ea2510319.png">

### for line height

In general, VSCode adjusts the line height by calculating with some properties of fonts. SF Mono Square and the original SF Mono have this properties and VSCode inserts some spaces between lines even if `lineHeight == 0`. It is the spec.

So if you feel annoying the extra space, you should supply the same value as the font size into Line Height.

**Comment by pddg** [comment]
@delphinus It's working as I expected. Thank you!

**Comment by delphinus** [comment]
welcome ;) I will investigate further, later.

**Comment by shungo27** [comment]
I can not see full-width space with "SF Mono 1x2", "SF Mono Square".

**Comment by delphinus** [comment]
@pddg Sorry for toooo late. This is fixed in the release v3.1.0, I think. Check it out.
