### ISSUE TITLE
Feature Request: Japenese font size(letter-spacing)

### ISSUE THREAD

**Issue by shungo27** [delphinus/homebrew-sfmono-square#9]
アルファベットや数字のフォントが好きで Ricty から SF Mono への乗り換えを考えています。ただ、日本語フォントは文字間が空きすぎていて、Ricty の方が読みやすいと感じます。

Ricty と比べると日本語フォントが小さいからかもしれません。英語フォントも Ricty と比べると若干小さいので、エディターの設定でフォントサイズを Ricty の時よりも大きくしています。

様々な調整の末このサイズに行き着いたのだとは思いますが、日本語フォントの文字を若干大きくするなどして日本語の文字間をもう少し詰めたりすることは可能ですか?

日本語ですみません。もし英語で書く必要があれば直します!

**Comment by delphinus** [comment]
issue は日本語でも結構ですよ！（と書いておけばよかったですね）

Migu1M 由来の全角文字は[この割合][]で縮小して合成しています。現在は 82% です。ここを修正すれば好みの大きさにできます。

[この割合]: https://github.com/delphinus/homebrew-sfmono-square/blob/849346d8554429ac08ca137e88c82efa6df50233/src/migu1m.py#L12

82% という値を決めたのはフィーリングだったので、並べて細かく比較して決めたわけではありません。これを機にちょっとやってみますね。

**Comment by delphinus** [comment]
ちなみに、英字フォントが Ricty より小さくなるのは SF Mono のグリフの縦横比が 1:2 でないためなので、これはもうしょうがないかと思っています。逆に、Migu 1M の縦横比を SF Mono（黄金比）に合わせるということもできますが、そうすると全角文字の間にもっと大きな隙間ができます。

詳しくは [Qiita の記事][]にも書いています。

[Qiita の記事]: https://qiita.com/delphinus/items/f472eb04ff91daf44274

**Comment by shungo27** [comment]
Ruby も Python も触ったことがなく、フォントも作ったことがなかったので合成の仕方がわからなくて時間がかかってしまいましたが、雰囲気でいじってたら作れたので(笑)いくつかパターンを検証してみました。

確かに、82% くらいだとアルファベットと日本語の大きさが近くなって良いのかもしれませんね。ただやはり日本語の部分だけを見ていると文字間がどうしても気になってしまい、自分の妥協点としては 90% くらいがちょうどいいと感じました。

インストール時のオプションでこの辺が調整できるような仕組みがあると良いのかもしれません。

**Comment by delphinus** [comment]
ありがとうございます。Ricty （Inconsolata）と比べるとアルファベットの高さが低いため、そのままではどうしても全角文字に隙間ができてしまいますね。Osaka は全角文字が太すぎてアルファベットと釣り合いが取れていないため、やはり Ricty くらいが読みやすく感じます。

僕の方でも試してみました。ターミナル（iTerm2）で Vim の日本語ヘルプを表示したものです。94% は明らかに詰まりすぎ（そしてアルファベットの大きさとあっていない）ように見えますので、86% か 90% が適当そうです。

もう少し自分でも使ってみてデフォルトの値を決めたいと思います。

* [SFMonoSquare-082.zip](https://github.com/delphinus/homebrew-sfmono-square/files/3440012/SFMonoSquare-082.zip)
* [SFMonoSquare-086.zip](https://github.com/delphinus/homebrew-sfmono-square/files/3440014/SFMonoSquare-086.zip)
* [SFMonoSquare-090.zip](https://github.com/delphinus/homebrew-sfmono-square/files/3440015/SFMonoSquare-090.zip)
* [SFMonoSquare-094.zip](https://github.com/delphinus/homebrew-sfmono-square/files/3440016/SFMonoSquare-094.zip)

* 82% (default)

<img width="630" alt="スクリーンショット 0001-07-29 11 20 34" src="https://user-images.githubusercontent.com/1239245/62018374-65879900-b1f5-11e9-820d-26cd09ba2823.png">

* 86%

<img width="630" alt="スクリーンショット 0001-07-29 11 07 06" src="https://user-images.githubusercontent.com/1239245/62018397-79cb9600-b1f5-11e9-9b42-681e85b8e320.png">

* 90%

<img width="630" alt="スクリーンショット 0001-07-29 11 10 22" src="https://user-images.githubusercontent.com/1239245/62018402-7d5f1d00-b1f5-11e9-8e64-e87894f84424.png">

* 94%

<img width="630" alt="スクリーンショット 0001-07-29 11 14 36" src="https://user-images.githubusercontent.com/1239245/62018404-7f28e080-b1f5-11e9-8e47-581e3cabf51b.png">

動画で並べてみましたがこれはよくわからないかも。

<img width="630" alt="cBUpKAXjyw" src="https://user-images.githubusercontent.com/1239245/62018819-45f17000-b1f7-11e9-97e8-2516756e6f79.gif">

**Comment by delphinus** [comment]
うむむ。大きさを変えてしばらく使ってみたのですが、やはり 82% より大きくすると違和感があります。これは僕のメインの環境である、iTerm2 + Vim にもよるのかもしれません。

| 82% |
|---|
| <img width="259" alt="スクリーンショット 0001-08-09 10 23 26" src="https://user-images.githubusercontent.com/1239245/62747550-f2e9a980-ba8f-11e9-93ba-db42d0d31c09.png"> |

| 86% |
|---|
| <img width="260" alt="スクリーンショット 0001-08-09 10 21 23" src="https://user-images.githubusercontent.com/1239245/62747547-ee24f580-ba8f-11e9-9801-813fdfe4dbb4.png"> |

ほんのわずかな差ではあるのですが、86% の方は半角文字（`0x80` とか `128`）が、周りの全角文字と比べて高さがずれているように感じられます。

そのためやはりデフォルトでは 82% のママとし、これをオプションか何かでインストール時に変更可能なようにしようと思います。

**Comment by shungo27** [comment]
検証ありがとうございました!

**Comment by delphinus** [comment]
こちら、`brew edit sfmono-square` で比率を自由に変えてビルドできるようにしました。

**Comment by callmezatiel** [comment]
Looks amazing
